# Generated by Django 5.1.5 on 2025-01-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertransaction',
            name='receiver',
        ),
    ]
