# Generated by Django 5.1.5 on 2025-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('in-house', 'In-house')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('request', 'Payment Request')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrequesttransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentrequesttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('in-house', 'In-house')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrequesttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('request', 'Payment Request')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('in-house', 'In-house')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('request', 'Payment Request')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('in-house', 'In-house')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('request', 'Payment Request')], max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('in-house', 'In-house')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('request', 'Payment Request')], max_length=100),
        ),
    ]
