# Generated by Django 5.1.5 on 2025-01-23 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
