# Generated by Django 5.1.5 on 2025-01-31 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('investments', '0001_initial'),
        ('loans', '0002_initial'),
        ('savings', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audittransaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to='investments.investment'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transactions', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minimum_shares_deposit_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_transactions', to='savings.goal'),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_account', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
