# Generated by Django 5.1.5 on 2025-01-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_deposittransaction_mpesa_result_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRequestTransaction',
        ),
    ]
