# Generated by Django 5.1.5 on 2025-01-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposittransaction_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittransaction',
            old_name='transaction_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='audittransaction',
            old_name='transaction_id',
            new_name='object_id',
        ),
    ]
