# Generated by Django 5.1.5 on 2025-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_transaction_type_audittransaction_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertransaction',
            name='mpesa_checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='transfertransaction',
            name='mpesa_phone_number',
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minimumsharesdeposittransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
