# Generated by Django 5.1.5 on 2025-01-31 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('transactions', '0005_remove_transfertransaction_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertransaction',
            name='receiver_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_goal', to='savings.goal'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='sender_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_goal', to='savings.goal'),
        ),
    ]
