# Generated by Django 5.1.5 on 2025-01-31 07:44

import accounts.models
import phonenumber_field.modelfields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_balance', models.PositiveIntegerField(default=0)),
                ('account_minimum_shares_balance', models.PositiveIntegerField(default=0)),
                ('account_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=25, prefix='ACC', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_full_member', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer_Account',
                'verbose_name_plural': 'Customer_Accounts',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('membership_number', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi1234567890', editable=False, length=10, max_length=20, prefix='217', primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=1000)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40)),
                ('identity_type', models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drives Licence'), ('international_passport', 'International Passport')], max_length=140)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('identity_image', models.ImageField(default='res/default.png', upload_to=accounts.models.user_directory_path)),
                ('date_of_birth', models.DateTimeField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path)),
                ('kra_pin', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('kyc_confirmed', models.BooleanField(default=False)),
                ('employment_status', models.CharField(blank=True, choices=[('unemployed', 'Unemployed'), ('self_employed', 'Self Employed'), ('employed', 'Employed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=40, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
