# Generated by Django 5.1.5 on 2025-01-26 08:56

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=25, prefix='217', primary_key=True, serialize=False, unique=True),
        ),
    ]
