# Generated by Django 5.1.5 on 2025-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_id_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('unemployed', 'Unemployed'), ('self_employed', 'Self Employed'), ('employed', 'Employed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=40, null=True),
        ),
    ]
