# Generated by Django 5.1.5 on 2025-01-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_kyc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-last_modified'], 'verbose_name': 'Customer_Account', 'verbose_name_plural': 'Customer_Accounts'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_status',
        ),
    ]
