# Generated by Django 5.1.5 on 2025-01-23 05:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_remove_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
