# Generated by Django 5.1.5 on 2025-01-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kyc_employment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='date',
        ),
    ]
