# Generated by Django 5.1.5 on 2025-01-28 12:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kyc_options_remove_kyc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='next_of_kin_contact',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='next_of_kin_relationship',
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='accounts.kyc')),
            ],
        ),
    ]
