# Generated by Django 5.1.5 on 2025-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_kyc_next_of_kin_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
