# Generated by Django 5.1.5 on 2025-01-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_minimum_shares_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
