# Generated by Django 5.1.5 on 2025-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_account_minimum_shares_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_full_member',
            field=models.BooleanField(default=False),
        ),
    ]
