# Generated by Django 5.1.5 on 2025-01-23 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_invested', models.DateTimeField(default=django.utils.timezone.now)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
