# Generated by Django 5.1.5 on 2025-01-31 07:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('total_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_profit_or_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('investment_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('return_on_investment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_invested', models.DateTimeField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_distributed', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_distributed', models.BooleanField(default=False)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.investmentaccount')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.investmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='investments.investmentaccount')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_user_investments', to='investments.investment')),
            ],
        ),
    ]
