# Generated by Django 5.1.5 on 2025-01-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
    ]
