# Generated by Django 5.1.5 on 2025-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_transactionhistory_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='cover_icon',
            field=models.CharField(default='star', max_length=20),
        ),
    ]
