# Generated by Django 5.1.5 on 2025-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_alter_goal_cover_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="color",
            field=models.CharField(default="#40A9FF", max_length=7),
        ),
    ]
