# Generated by Django 5.1.5 on 2025-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='admin', max_length=10),
        ),
    ]
